server:
  port: 8888
spring:
  application:
    name: shiroApp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myuser?characterEncoding=utf-8
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:config.xml
